### ISSUE TITLE
How can I get /au/personEntered from the simulator?

### ISSUE THREAD

**Issue by deemeetree** [Augmenta-tech/Augmenta-Simulator#2]
Hi!

I want to get `/au/personEntered` and `/au/personWillLeave` from the simulator. Is there any way to model this?

I want to specifically target events where the square touch each other, each time there's a contact.

Thank you

Dmitry

**Comment by Lyptik** [comment]
When clicking on remove points it sends a personwillleave signal.

When creating points also.
if you right click in the middle of the window it will create a point if you left click it will destroy it, effectively sending the entered and leave signal.
Since the fusion of the blobs happens from a limitation of the system you might have to build your own setup to model this. You can do your own simulator or modify one of the two available simulators code on github (processing or Unity).
There also might be a possible setup to replicate this without doing any code involving using two simulator and fusion, since fusion does merge the point in overlaping areas.
Setup would be :
two simulators as input source in fusion
putting some overlap on the sources

having one still point in the overlapping area from one source

moving with your mouse a point from te second source till it's fusionned by fusion

-> you might get the same "collision" behavior that I described in an earlier mail

Best

**Comment by alexbourgeois** [comment]
Hi,

The two events /au/personEntered and /au/personWillLeave are sent each time a point enter/leave the augmentaArea (defined in the area settings of the simulator).
As David said if you want to get those events for one point the easiest way would be to left/right click on the area to make a point appear/disappear on your cursor position.

If you want to get an event when 2 objects intersects each other you have to code an algorithm that will detects when 2 point bounding boxes (included in augmenta protocol) intersect each other :)
You don't need to use 2 simulators nor fusion for this.

Best regards,

Alex
